/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/hello-world': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Hello World */
    get: operations['core_api_hello_world']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/startup-report': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Startup Reports
     * @description Fetch all available startup reports.
     */
    get: operations['core_startup_report_public_api_get_startup_reports']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/startup-report/create': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Startup Reports
     * @description Create startup reports for each name in the provided list.
     */
    post: operations['core_startup_report_public_api_create_startup_reports']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/startup-report/delete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Delete Startup Reports
     * @description Delete startup reports for each ID in the provided list.
     */
    post: operations['core_startup_report_public_api_delete_startup_reports']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/startup-report/update-prompt': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Update Prompt
     * @description Create a new startup report prompt, preserving history of previous prompts.
     */
    post: operations['core_startup_report_public_api_update_prompt']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/startup-report/current-prompt': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Current Prompt
     * @description Fetch the most recent startup report prompt.
     *
     *     Returns an empty string if no prompt exists.
     */
    get: operations['core_startup_report_public_api_get_current_prompt']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** GetStartupReportsResponse */
    GetStartupReportsResponse: {
      /** Reports */
      reports: components['schemas']['StartupReportResponse'][]
    }
    /** StartupReportResponse */
    StartupReportResponse: {
      /** Id */
      id: number
      /** Name */
      name: string
      /** Created At */
      created_at: string
      /** Read By User */
      read_by_user: boolean
      /** Generation Status */
      generation_status: string
      /** Report Text */
      report_text: string
    }
    /** DefaultSuccessResponse */
    DefaultSuccessResponse: {
      /**
       * Success
       * @default true
       */
      success: boolean
    }
    /** CreateStartupReportsRequest */
    CreateStartupReportsRequest: {
      /** Names */
      names: string[]
    }
    /** DeleteStartupReportsRequest */
    DeleteStartupReportsRequest: {
      /** Report Ids */
      report_ids: number[]
    }
    /** UpdatePromptRequest */
    UpdatePromptRequest: {
      /** Prompt */
      prompt: string
    }
    /** GetCurrentPromptResponse */
    GetCurrentPromptResponse: {
      /** Prompt */
      prompt: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  core_api_hello_world: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  core_startup_report_public_api_get_startup_reports: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetStartupReportsResponse']
        }
      }
    }
  }
  core_startup_report_public_api_create_startup_reports: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateStartupReportsRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DefaultSuccessResponse']
        }
      }
    }
  }
  core_startup_report_public_api_delete_startup_reports: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteStartupReportsRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DefaultSuccessResponse']
        }
      }
    }
  }
  core_startup_report_public_api_update_prompt: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePromptRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DefaultSuccessResponse']
        }
      }
    }
  }
  core_startup_report_public_api_get_current_prompt: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GetCurrentPromptResponse']
        }
      }
    }
  }
}
