# Generated by Django 5.2.7 on 2025-10-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupReportDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_user', models.BooleanField(default=False)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('report_text', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_startupreport',
            },
        ),
        migrations.CreateModel(
            name='StartupReportPromptDbModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
            ],
            options={
                'db_table': 'core_startupreportprompt',
            },
        ),
    ]
